#spring.application.name=BatchApp
### DataSource

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.batch.jdbc.initialize-schema=always
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Batch ? tells it to auto-create batch metadata tables in your DB
