#spring.application.name=BatchApp
### DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/cptcodes
spring.datasource.username=root
spring.datasource.password=0987
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.batch.jdbc.initialize-schema=always
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Batch ? tells it to auto-create batch metadata tables in your DB
